// <auto-generated />
using System;
using BarangKeluarDinas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarangKeluarDinas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610014101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("BarangKeluarDinas.Models.ItemBarangKeluar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("JumlahBawa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JumlahDipakai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keterangan")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaUnit")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoMaterialPengembalian")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PK_GI")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SRM")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("STN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TugasanDinasId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitDipakai")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitLama")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TugasanDinasId");

                    b.ToTable("ItemBarangKeluar");
                });

            modelBuilder.Entity("BarangKeluarDinas.Models.TugasanDinas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BawaBarang")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jobdesk")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LokasiDinas")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PIC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalDari")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalKe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TugasanDinas");
                });

            modelBuilder.Entity("BarangKeluarDinas.Models.ItemBarangKeluar", b =>
                {
                    b.HasOne("BarangKeluarDinas.Models.TugasanDinas", "TugasanDinas")
                        .WithMany("SenaraiBarang")
                        .HasForeignKey("TugasanDinasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TugasanDinas");
                });

            modelBuilder.Entity("BarangKeluarDinas.Models.TugasanDinas", b =>
                {
                    b.Navigation("SenaraiBarang");
                });
#pragma warning restore 612, 618
        }
    }
}
